### ISSUE TITLE
Deserialization: floating point bounds check does not permit messages with NaN

### ISSUE THREAD

**Issue by oysstu** [ros2/rosidl_python#162]
## Bug report

**Required Info:**

- Operating System: Linux 
- Installation type: Source, master
- Version or commit hash: 3dc587255effce330db05e045a5cead78df28339
- DDS implementation: Fast-RTPS
- Client library (if applicable): rclpy

#### Steps to reproduce issue
Running deserialize_message(serialized_message: bytes, message_type) on a message containing a field set to NaN triggers the bounds check added in #128.

assert value >= -3.402823e+38 and value <= 3.402823e+38,
AssertionError: The 'current' field must be a float in [-3.402823e+38, 3.402823e+38]

#### Expected behavior
The NaN value should be converted to a NaN in python.

The [BatteryState](https://github.com/ros2/common_interfaces/blob/b7e2ad503e1648468b1dc766c43aac12cc9aee5a/sensor_msgs/msg/BatteryState.msg) message, for example, uses NaNs to flag values that are not measured.

#### Actual behavior
The conversion triggers an assertion, and fails to deserialize.

**Comment by sloretz** [comment]
I'm able to reproduce. The check happens on the setter for a message field of types `float`/`float32` and `double`/`float64` (.idl/.msg). It looks like the check's purpose is to make sure the value can be represented by the storage type. While the ticket mentions NaN, the logic also fails for positive and negative `inf`.

```python3
>>> from sensor_msgs.msg import BatteryState
>>> b = BatteryState()
>>> b.temperature = float('nan')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sloretz/ws/ros2/install/sensor_msgs/local/lib/python3.10/dist-packages/sensor_msgs/msg/_battery_state.py", line 424, in temperature
    assert value >= -3.402823e+38 and value <= 3.402823e+38, \
AssertionError: The 'temperature' field must be a float in [-3.402823e+38, 3.402823e+38]
>>> b.temperature = float('inf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sloretz/ws/ros2/install/sensor_msgs/local/lib/python3.10/dist-packages/sensor_msgs/msg/_battery_state.py", line 424, in temperature
    assert value >= -3.402823e+38 and value <= 3.402823e+38, \
AssertionError: The 'temperature' field must be a float in [-3.402823e+38, 3.402823e+38]
>>> from sensor_msgs.msg import RelativeHumidity
>>> r = RelativeHumidity()
>>> r.variance =  float('nan')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sloretz/ws/ros2/install/sensor_msgs/local/lib/python3.10/dist-packages/sensor_msgs/msg/_relative_humidity.py", line 170, in variance
    assert value >= -1.7976931348623157e+308 and value <= 1.7976931348623157e+308, \
AssertionError: The 'variance' field must be a double in [-1.7976931348623157e+308, 1.7976931348623157e+308]
>>> r.variance =  float('inf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sloretz/ws/ros2/install/sensor_msgs/local/lib/python3.10/dist-packages/sensor_msgs/msg/_relative_humidity.py", line 170, in variance
    assert value >= -1.7976931348623157e+308 and value <= 1.7976931348623157e+308, \
AssertionError: The 'variance' field must be a double in [-1.7976931348623157e+308, 1.7976931348623157e+308]

```
