### ISSUE TITLE
Failed   <<< rosidl_generator_py [7.26s, exited with code 1] 

### ISSUE THREAD

**Issue by Smit-tay** [ros2/rosidl_python#219]
## Bug report

**Required Info:**

- Operating System:
Fedora 41 Linux
- Installation type:
Source
- Version or commit hash:
Jazzy
- DDS implementation:
Default
- Client library (if applicable):
Unknown

#### Expected behavior
build without error

#### Actual behavior
```
starting >>> rosidl_generator_py
Starting >>> rosidl_typesupport_cpp                                                                                          
--- stderr: rosidl_generator_py                                                                                              
CMake Error at /home/me/ros2_jazzy/install/rosidl_adapter/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:57 (message):
  execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
  rosidl_generator_py --arguments-file
  /home/me/ros2_jazzy/build/rosidl_generator_py/rosidl_adapter__arguments__rosidl_generator_py_custom.json
  --output-dir
  /home/me/ros2_jazzy/build/rosidl_generator_py/rosidl_adapter/rosidl_generator_py
  --output-file
  /home/me/ros2_jazzy/build/rosidl_generator_py/rosidl_adapter/rosidl_generator_py_custom.idls)
  returned error code 1:

  AttributeError processing template 'msg.idl.em'

  Traceback (most recent call last):

    File "/home/me/ros2_jazzy/install/rosidl_adapter/lib/python3.13/site-packages/rosidl_adapter/resource/__init__.py", line 51, in evaluate_template
      em.BUFFERED_OPT: True,
      ^^^^^^^^^^^^^^^

  AttributeError: module 'em' has no attribute 'BUFFERED_OPT'



  During handling of the above exception, another exception occurred:



  Traceback (most recent call last):

    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "/home/me/ros2_jazzy/install/rosidl_adapter/lib/python3.13/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
               ~~~~^^
    File "/home/me/ros2_jazzy/install/rosidl_adapter/lib/python3.13/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
          pathlib.Path(basepath), args.package_name,
          pathlib.Path(relative_path), output_dir)
    File "/home/me/ros2_jazzy/install/rosidl_adapter/lib/python3.13/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
          package_dir, package_name, interface_file, output_dir / 'msg')
    File "/home/me/ros2_jazzy/install/rosidl_adapter/lib/python3.13/site-packages/rosidl_adapter/msg/__init__.py", line 39, in convert_msg_to_idl
      expand_template('msg.idl.em', data, output_file, encoding='iso-8859-1')
      ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/me/ros2_jazzy/install/rosidl_adapter/lib/python3.13/site-packages/rosidl_adapter/resource/__init__.py", line 23, in expand_template
      content = evaluate_template(template_name, data)
    File "/home/me/ros2_jazzy/install/rosidl_adapter/lib/python3.13/site-packages/rosidl_adapter/resource/__init__.py", line 69, in evaluate_template
      _interpreter.shutdown()
      ^^^^^^^^^^^^^^^^^^^^^

  AttributeError: 'NoneType' object has no attribute 'shutdown'

Call Stack (most recent call first):
  /home/me/ros2_jazzy/install/rosidl_cmake/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:132 (rosidl_adapt_interfaces)
  CMakeLists.txt:50 (rosidl_generate_interfaces)


---
Failed   <<< rosidl_generator_py [7.26s, exited with code 1]

```

**Comment by Smit-tay** [comment]
I'm starting to worry about having to use containers for everything I want to do
